### ISSUE TITLE
error writing to firestore

### ISSUE THREAD

**Issue by 1-Anirudh** [1-Anirudh/ResearchFinder#3]
Facing an error while writing to firestore, Need to analyze and user proper references as aligned with firebase norms. Doc references and referencing collections within docs to be done carefully.
![add-details](https://github.com/user-attachments/assets/f251aa27-6dcb-423d-8336-6ec70dcbd834)
![add-details_](https://github.com/user-attachments/assets/31af58d1-6544-401f-adec-9fa4e7b881aa)

**Comment by 1-Anirudh** [comment]
resolved !! added trimmed ID

**Comment by ShaikFayaz6** [comment]
Resolved
