### ISSUE TITLE
incorrect reference segments

### ISSUE THREAD

**Issue by 1-Anirudh** [1-Anirudh/ResearchFinder#4]
references segments for documents must be even but for doc in users has a single segment "Registration failed: Invalid document reference. Document references must have an even number of segments, but users has 1."

![refernces_](https://github.com/user-attachments/assets/c46ffa3c-c870-453f-9ad2-5bc53b96c00e)

**Comment by 1-Anirudh** [comment]
resolved !!

**Comment by ShaikFayaz6** [comment]
Resolved
