### ISSUE TITLE
undefined responses from ejs

### ISSUE THREAD

**Issue by 1-Anirudh** [1-Anirudh/ResearchFinder#5]
some error while getting response from feedback.ejs, undefined fields and type errors.
![feedback](https://github.com/user-attachments/assets/50366b03-051e-450d-92d9-a91914b144af)
![feedback_](https://github.com/user-attachments/assets/5309f275-585a-4448-bac2-55689dca84b9)

**Comment by 1-Anirudh** [comment]
resolved !!

**Comment by Smaranareddy6** [comment]
Issue Resolved
