### ISSUE TITLE
invalid data fields

### ISSUE THREAD

**Issue by 1-Anirudh** [1-Anirudh/ResearchFinder#6]
Error while submitting feedback "Function addDoc() called with invalid data. Unsupported field value: undefined (found in field feedback in document feedbacks/dusVDlFCFzEB42saaWM9"
![feedback1](https://github.com/user-attachments/assets/fd7cc3a0-67dd-4bf3-8e15-3ba062fa3def)
![feedback1_](https://github.com/user-attachments/assets/a73377d6-bdbf-44a4-a09e-b488661611d3)

**Comment by 1-Anirudh** [comment]
resolved !!

**Comment by Smaranareddy6** [comment]
Issue Resolved
