### ISSUE TITLE
styling not working for landing.ejs

### ISSUE THREAD

**Issue by 1-Anirudh** [1-Anirudh/ResearchFinder#7]
had a separate css file for the landing page but ejs is not styled according to it. had to add the css inline within the landing.ejs
![landing](https://github.com/user-attachments/assets/fbbad466-b1b7-4c31-a413-5f0eaa9b358f)

**Comment by 1-Anirudh** [comment]
resolved !!
![landing_r](https://github.com/user-attachments/assets/ad95cd1d-e4d5-405a-8392-fe42c7104819)

**Comment by Smaranareddy6** [comment]
Resolved!

**Comment by Smaranareddy6** [comment]
Resolved!
